#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${ROOT_DIR}/scripts/lib/bridge_env.sh"
bridge_env_load "${ROOT_DIR}"

ssh -t \
  -o StrictHostKeyChecking=accept-new \
  -J "${PI_USER}@${PI_HOST}" \
  "${GO2_USER}@${GO2_HOST}" \
  "GO2_RVIZ_SEND_HOST='${GO2_SEND_HOST}' GO2_RVIZ_SEND_PORT='${GO2_SEND_PORT}' GO2_RVIZ_RECV_HOST='${GO2_RECV_HOST}' GO2_RVIZ_RECV_PORT='${GO2_RECV_PORT}' GO2_RVIZ_PROTOCOL='${GO2_RVIZ_PROTOCOL:-binary}' GO2_RVIZ_TOPIC_ALLOWLIST='${GO2_RVIZ_TOPIC_ALLOWLIST:-default}' GO2_RVIZ_TOPIC_RATE_LIMITS='${GO2_RVIZ_TOPIC_RATE_LIMITS:-}' GO2_RVIZ_DEBUG_ALL_TOPICS='${GO2_RVIZ_DEBUG_ALL_TOPICS:-false}' GO2_RVIZ_QUEUE_CAPACITY='${GO2_RVIZ_QUEUE_CAPACITY:-32}' GO2_RVIZ_MAX_FRAME_BYTES='${GO2_RVIZ_MAX_FRAME_BYTES:-16777216}' GO2_RVIZ_MAX_BUFFER_BYTES='${GO2_RVIZ_MAX_BUFFER_BYTES:-20971520}' GO2_RVIZ_WRITE_TIMEOUT='${GO2_RVIZ_WRITE_TIMEOUT:-2.0}' GO2_RVIZ_TF_MAX_HZ='${GO2_RVIZ_TF_MAX_HZ:-20.0}' GO2_RVIZ_IMAGE_MAX_HZ='${GO2_RVIZ_IMAGE_MAX_HZ:-2.0}' GO2_RVIZ_POINTCLOUD_MAX_HZ='${GO2_RVIZ_POINTCLOUD_MAX_HZ:-0.5}' GO2_CAMERA_ENABLE='${GO2_CAMERA_ENABLE:-false}' GO2_CAMERA_FPS='${GO2_CAMERA_FPS:-${GO2_VIDEO_FPS:-5}}' GO2_JOINT_TF_ENABLE='${GO2_JOINT_TF_ENABLE:-true}' GO2_LOWSTATE_TOPICS='${GO2_LOWSTATE_TOPICS:-lowstate,lf/lowstate}' GO2_JOINT_TF_HZ='${GO2_JOINT_TF_HZ:-20.0}' GO2_VIDEO_ENABLE='false' /home/unitree/go2_navigation_project/scripts/start_live_mapping_with_rviz_bridge.sh"
